language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/travis-build.sh
  - ./scripts/test.sh
after_success:
  - ./scripts/travis-success.sh
notifications:
  email:
    on_success: never
    on_failure: always